### ISSUE TITLE
Vulnerable to chosen-plaintext attacks

### ISSUE THREAD

**Issue by kormal** [mmcc1/crystalline#2]
Each bit in a ciphertext is related to exactly 1 bit from the corresponding plaintext, because bits are only ever swapped and flipped. This relationship depends on the key, salt, message-length and number of rounds, but not on the content of the plaintext. This makes your cipher vulnerable to chosen-plaintext attacks.

For example, imagine that an attacker has gained access to an oracle `byte[] Encrypt(byte[] plaintext)`, and they wish to decrypt a message that has been encrypted by that oracle. The attacker does not know the key, salt or number of rounds - they can only ask the oracle the encrypt messages.

The attacker starts by encrypting a message of the same length and notes the resulting ciphertext. Then, the attacker flips the first bit of the original message and encrypts this new message. They compare the new ciphertext with the first ciphertext and note which bit has been flipped. They repeat this process for every bit in the message. Now, the attacker knows exactly which bit ends up where, and which bits get flipped. This allows them to decrypt not only the message they wanted to decrypt in the first place, but any other message of the same length. They're even able to produce ciphertexts of their own, without having to obtain the key, salt or number of rounds.

**Comment by mmcc1** [comment]
It is not vulnerable unless there is key reuse.  The amount of entropy in 16KB keys and salts is very high.  Also, with lattice, different keys and salts can be layered.

**Comment by kormal** [comment]
The documentation states that Crystalline is 'Designed to be as secure as a one-time pad, without a weakness due to the use of repeating keys', but now you're saying that keys should not be reused?

That makes this cipher as impractical for most use-cases as a one-time pad... why not use an OTP directly instead?

**Comment by mmcc1** [comment]
Its just another option.  OTP require keys the same size as the plaintext, so this is more compact.  So, it sits in the middle ground between AES and an OTP.
